node {
    stage 'build'
        openshiftBuild(bldCfg: 'gitbook-centos-docker')
    stage 'scan image'

        aqua hideBase: false, hostedImage: 'security-build-test/gitbook-centos-docker', localImage: '', locationType: 'hosted', notCompliesCmd: '', onDisallowed: 'fail', registry: 'OpenShift', showNegligible: false

    stage 'deploy'
        sh "oc rollout latest dc/gitbook-centos-docker"

    stage 'ask for promotion'
        input id: 'Approve01', message: 'Wanna push to prod?????', ok: 'HANG TIGHT!'

    stage 'tag and promote'
        sh "oc tag gitbook-centos-docker:latest gitbook-centos-docker:prod"

}
