node {
    stage 'build'
        openshiftBuild(bldCfg: 'gitbook-centos-docker')
    stage 'scan'
        aqua hideBase: false, hostedImage: '', localImage: '', locationType: 'local', notCompliesCmd: '', onDisallowed: 'ignore', registry: '', showNegligible: false
    stage 'deploy'
        sh "oc rollout latest dc/gitbook-centos-docker"

    stage 'ask for promotion'
        input id: 'Approve01', message: 'Wanna push to prod?????', ok: 'HANG TIGHT!'

    stage 'tag and promote'
        sh "oc tag gitbook-centos-docker:latest gitbook-centos-docker:prod"

}
