node {
    stage 'build'
        openshiftBuild(bldCfg: 'gitbook-centos-docker')
    stage 'scan image'
        withCredentials([usernamePassword(credentialsId: '93f8782b-6eb0-42e8-a24b-a2ecddb8cbf5', passwordVariable: 'password', usernameVariable: 'username')]) {
            sh '''
            docker login -e=unused-u=$username -p=$password docker-registry-default.apps.54.197.37.244.xip.io
            '''
        }
        aqua hideBase: false, hostedImage: 'security-build-test/gitbook-centos-docker', localImage: '', locationType: 'hosted', notCompliesCmd: '', onDisallowed: 'fail', registry: 'OpenShift', showNegligible: false

    stage 'deploy'
        sh "oc rollout latest dc/gitbook-centos-docker"

    stage 'ask for promotion'
        input id: 'Approve01', message: 'Wanna push to prod?????', ok: 'HANG TIGHT!'

    stage 'tag and promote'
        sh "oc tag gitbook-centos-docker:latest gitbook-centos-docker:prod"

}
